/* ==========================================================================
   Department workspaces — which documents each department owns, and the
   register definition (fields, status workflow, sample rows) for each one.
   dept.js renders every register from these definitions; BOM is handled by
   its own editor in bom.js.
   ========================================================================== */

const PROD_LINES = ["ไลน์ประกอบ 1", "ไลน์ประกอบ 2", "ไลน์ประกอบ 3", "ไลน์เชื่อม", "ไลน์พ่นสี", "ไลน์ทดสอบ"];

// tone → pill class: neutral (gray), info (blue), warning, good, critical
const DOC_TONE_PILL = {
  neutral: "pill-eliminate",
  info: "pill-schedule",
  warning: "pill-warning",
  good: "pill-good",
  critical: "pill-critical",
};

const DEPT_WORKSPACES = [
  {
    id: "rnd",
    name: "R&D / วิศวกรรม",
    desc: "ควบคุมแบบ รายการวัสดุ และการเปลี่ยนแปลงทางวิศวกรรม — ทุกการเปลี่ยนแปลงเริ่มจาก ECR → อนุมัติ → ออก EO → ปรับ BOM / WI / แบบ",
    docTypes: ["ecr", "eo", "bom", "wi", "dwg"],
    tools: [{ view: "workorder", label: "ใบสั่งผลิต & การเบิกวัสดุ" }, { view: "makeorbuy", label: "Make-or-Buy" }],
  },
  {
    id: "plan",
    name: "วางแผนการผลิต (PC)",
    desc: "แปลงคำสั่งซื้อลูกค้าเป็นแผนผลิตและความต้องการวัสดุ ให้สอดคล้องกับกำลังการผลิต",
    docTypes: ["plan", "mrq"],
    tools: [{ view: "schedule", label: "Master Schedule" }, { view: "capacity", label: "Capacity Planning" }, { view: "priority", label: "Priority Matrix" }],
  },
  {
    id: "prod",
    name: "ฝ่ายผลิต",
    desc: "บันทึกผลผลิตรายวัน เบิกวัสดุตามใบสั่งผลิต และรายงานเหตุการณ์ด้านความปลอดภัยจากหน้างาน",
    docTypes: ["dpr", "mreq", "saf"],
    tools: [{ view: "workorder", label: "ใบสั่งผลิต & BOM" }, { view: "mytasks", label: "งานของฉัน" }, { view: "resource", label: "กำลังคน / เครื่องจักร" }],
  },
  {
    id: "qc",
    name: "QC / ตรวจสอบคุณภาพ",
    desc: "ตรวจรับวัตถุดิบ ตรวจก่อนส่งมอบ บันทึกของเสีย (NCR) และติดตามการแก้ไขป้องกัน (CAPA)",
    docTypes: ["ncr", "capa", "iqc", "fi"],
    tools: [{ view: "resource", label: "เครื่องมือวัด / สอบเทียบ" }],
  },
  {
    id: "pur",
    name: "จัดซื้อ",
    desc: "ขอราคาเปรียบเทียบก่อนออก PO และประเมินผลงานผู้ขายเป็นรอบ",
    docTypes: ["rfq", "sev"],
    tools: [{ view: "procurement", label: "PR / PO / ซัพพลายเออร์" }, { view: "makeorbuy", label: "Make-or-Buy" }],
  },
  {
    id: "wh",
    name: "คลังสินค้า / พัสดุ",
    desc: "รับของเข้าคลังตาม PO และตรวจนับสต็อกให้ยอดในระบบตรงกับของจริง",
    docTypes: ["grn", "stk"],
    tools: [{ view: "workorder", label: "การเบิกวัสดุประกอบ" }, { view: "procurement", label: "สถานะ PO" }],
  },
  {
    id: "mt",
    name: "ซ่อมบำรุง",
    desc: "รับแจ้งซ่อมจากหน้างาน และทำแผนบำรุงรักษาเชิงป้องกัน (PM) ไม่ให้เครื่องหยุดกะทันหัน",
    docTypes: ["mtr", "pm"],
    tools: [{ view: "resource", label: "สถานะเครื่องจักร" }],
  },
  {
    id: "sales",
    name: "ขาย / บริการลูกค้า",
    desc: "รับคำสั่งซื้อจากลูกค้า ส่งต่อให้ฝ่ายวางแผน และติดตามข้อร้องเรียนจนปิดเรื่อง",
    docTypes: ["so", "cc"],
    tools: [{ view: "schedule", label: "Master Schedule" }],
  },
];

// Field types: text, textarea, number, date, select (options), model, line, ref (refType = another doc type id)
const DOC_TYPES = {
  /* ---------------- R&D ---------------- */
  ecr: {
    name: "ECR — คำขอเปลี่ยนแปลงทางวิศวกรรม",
    abbr: "ECR",
    prefix: "ECR",
    purpose: "จุดเริ่มต้นของทุกการเปลี่ยนแปลงแบบ/ชิ้นส่วน ระบุเหตุผลและผลกระทบก่อนอนุมัติ",
    fields: [
      { key: "title", label: "สิ่งที่ขอเปลี่ยนแปลง", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "reason", label: "เหตุผล", type: "select", options: ["ปัญหาคุณภาพ", "ลดต้นทุน", "ลูกค้าร้องขอ", "ปรับปรุงการผลิต", "ชิ้นส่วนเลิกผลิต/หาไม่ได้", "ความปลอดภัย"] },
      { key: "owner", label: "ผู้ขอ", type: "text" },
      { key: "date", label: "วันที่ขอ", type: "date" },
      { key: "detail", label: "รายละเอียด / ผลกระทบต่อต้นทุน-สต็อก-งานที่ผลิตอยู่", type: "textarea" },
    ],
    cols: ["model", "reason", "owner", "date"],
    statuses: [["ร่าง", "neutral"], ["รอพิจารณา", "warning"], ["อนุมัติ", "good"], ["ไม่อนุมัติ", "critical"], ["ปิดแล้ว", "neutral"]],
    flow: ["ร่าง", "รอพิจารณา", "อนุมัติ", "ปิดแล้ว"],
    closed: ["ไม่อนุมัติ", "ปิดแล้ว"],
    samples: [
      { no: "ECR-2026-001", status: "อนุมัติ", title: "เปลี่ยนวัสดุใบมีดตัดอ้อยเป็นเหล็ก SK5 ชุบแข็ง", model: "YT6500", reason: "ปัญหาคุณภาพ", owner: "ฝ่ายวิศวกรรม", date: "2026-09-02", detail: "ใบมีดเดิมสึกเร็วกว่ากำหนด ลูกค้าแจ้ง 3 ราย — ต้นทุน +180 บาท/ชิ้น" },
      { no: "ECR-2026-002", status: "รอพิจารณา", title: "ย้ายตำแหน่งจุดยึดสายไฮดรอลิกหลบโซ่ลำเลียง", model: "YT7500", reason: "ปรับปรุงการผลิต", owner: "ไลน์ประกอบ 2", date: "2026-09-15", detail: "ประกอบยาก สายเสียดสีโซ่" },
    ],
  },
  eo: {
    name: "EO / ECN — ใบสั่งเปลี่ยนแปลงทางวิศวกรรม",
    abbr: "EO",
    prefix: "EO",
    purpose: "คำสั่งให้ปฏิบัติตามการเปลี่ยนแปลงที่อนุมัติแล้ว ระบุว่ามีผลตั้งแต่ล็อต/เครื่องไหน",
    fields: [
      { key: "title", label: "เรื่อง", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "ref", label: "อ้างอิง ECR", type: "ref", refType: "ecr" },
      { key: "effective", label: "มีผลตั้งแต่ (ล็อต / เลขเครื่อง)", type: "text" },
      { key: "parts", label: "ชิ้นส่วน/เอกสารที่ได้รับผลกระทบ (BOM, WI, แบบ)", type: "text" },
      { key: "owner", label: "วิศวกรผู้รับผิดชอบ", type: "text" },
      { key: "date", label: "วันที่ออก", type: "date" },
    ],
    cols: ["model", "ref", "effective", "date"],
    statuses: [["ร่าง", "neutral"], ["รออนุมัติ", "warning"], ["อนุมัติแล้ว", "info"], ["แจ้งหน้างานแล้ว", "info"], ["มีผลใช้งาน", "good"], ["ยกเลิก", "critical"]],
    flow: ["ร่าง", "รออนุมัติ", "อนุมัติแล้ว", "แจ้งหน้างานแล้ว", "มีผลใช้งาน"],
    closed: ["มีผลใช้งาน", "ยกเลิก"],
    samples: [
      { no: "EO-2026-001", status: "แจ้งหน้างานแล้ว", title: "ใช้ใบมีด SK5 ชุบแข็งแทนรุ่นเดิม", model: "YT6500", ref: "ECR-2026-001", effective: "ล็อต 2 เป็นต้นไป", parts: "BOM YT6500 Rev.B, WI-2026-001", owner: "ฝ่ายวิศวกรรม", date: "2026-09-08" },
    ],
  },
  wi: {
    name: "WI — วิธีการปฏิบัติงาน (Work Instruction)",
    abbr: "WI",
    prefix: "WI",
    purpose: "ขั้นตอนทำงานมาตรฐานประจำสถานีงาน ให้ทุกคนทำเหมือนกันและใช้สอนพนักงานใหม่",
    fields: [
      { key: "title", label: "ชื่อขั้นตอนงาน", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "line", label: "สถานีงาน / ไลน์", type: "line" },
      { key: "rev", label: "Revision", type: "text" },
      { key: "ref", label: "อ้างอิง EO (ถ้ามี)", type: "ref", refType: "eo" },
      { key: "owner", label: "ผู้จัดทำ", type: "text" },
      { key: "date", label: "วันที่มีผล", type: "date" },
      { key: "link", label: "ลิงก์ไฟล์เอกสาร (Drive/SharePoint)", type: "text" },
    ],
    cols: ["model", "line", "rev", "date"],
    statuses: [["ร่าง", "neutral"], ["รอทบทวน", "warning"], ["อนุมัติใช้งาน", "good"], ["ยกเลิกใช้", "critical"]],
    flow: ["ร่าง", "รอทบทวน", "อนุมัติใช้งาน"],
    closed: ["ยกเลิกใช้"],
    samples: [
      { no: "WI-2026-001", status: "รอทบทวน", title: "การติดตั้งใบมีดตัดอ้อยและขันแรงบิด", model: "YT6500", line: "ไลน์ประกอบ 1", rev: "C", ref: "EO-2026-001", owner: "ฝ่ายวิศวกรรม", date: "2026-09-20", link: "" },
      { no: "WI-2026-002", status: "อนุมัติใช้งาน", title: "ขั้นตอนทดสอบแรงดันระบบไฮดรอลิก", model: "", line: "ไลน์ทดสอบ", rev: "A", ref: "", owner: "ไลน์ทดสอบ", date: "2026-06-01", link: "" },
    ],
  },
  dwg: {
    name: "ทะเบียนแบบ (Drawing Register)",
    abbr: "DWG",
    prefix: "DWG",
    purpose: "รู้ว่าแบบชิ้นส่วนแต่ละตัวใช้ Rev. ไหนอยู่ ป้องกันหน้างานใช้แบบเก่า",
    fields: [
      { key: "title", label: "ชื่อชิ้นส่วน / แบบ", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "rev", label: "Revision", type: "text" },
      { key: "owner", label: "ผู้ออกแบบ", type: "text" },
      { key: "date", label: "วันที่ออกแบบ", type: "date" },
      { key: "link", label: "ลิงก์ไฟล์แบบ (PDF/CAD)", type: "text" },
    ],
    cols: ["model", "rev", "owner", "date"],
    statuses: [["กำลังออกแบบ", "info"], ["รอตรวจแบบ", "warning"], ["อนุมัติ (Released)", "good"], ["ยกเลิก", "critical"]],
    flow: ["กำลังออกแบบ", "รอตรวจแบบ", "อนุมัติ (Released)"],
    closed: ["ยกเลิก"],
    samples: [
      { no: "DWG-2026-001", status: "อนุมัติ (Released)", title: "ใบมีดตัดอ้อย SK5", model: "YT6500", rev: "B", owner: "ฝ่ายวิศวกรรม", date: "2026-09-05", link: "" },
    ],
  },
  bom: {
    name: "BOM — รายการวัสดุต่อรุ่น",
    abbr: "BOM",
    special: true,
    purpose: "สร้าง แก้ไข คัดลอก และออก Revision ของ BOM แต่ละรุ่น — เชื่อมกับหน้าใบสั่งผลิตโดยตรง",
  },

  /* ---------------- Planning ---------------- */
  plan: {
    name: "แผนการผลิตประจำสัปดาห์",
    abbr: "PLN",
    prefix: "PLN",
    purpose: "แผนว่าสัปดาห์นี้แต่ละไลน์ผลิตอะไร กี่คัน ใช้ประชุมเช้าและติดตามผล",
    fields: [
      { key: "title", label: "ช่วงแผน (เช่น สัปดาห์ที่ 40)", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "qty", label: "จำนวน (คัน)", type: "number" },
      { key: "line", label: "ไลน์ผลิต", type: "line" },
      { key: "owner", label: "ผู้วางแผน", type: "text" },
      { key: "date", label: "วันเริ่ม", type: "date" },
    ],
    cols: ["model", "qty", "line", "date"],
    statuses: [["ร่าง", "neutral"], ["อนุมัติแผน", "info"], ["กำลังดำเนินการ", "warning"], ["เสร็จตามแผน", "good"], ["ไม่เป็นไปตามแผน", "critical"]],
    flow: ["ร่าง", "อนุมัติแผน", "กำลังดำเนินการ", "เสร็จตามแผน"],
    closed: ["เสร็จตามแผน", "ไม่เป็นไปตามแผน"],
    samples: [
      { no: "PLN-2026-001", status: "กำลังดำเนินการ", title: "สัปดาห์ที่ 39", model: "YT6500", qty: 3, line: "ไลน์ประกอบ 1", owner: "ฝ่ายวางแผน", date: "2026-09-21" },
    ],
  },
  mrq: {
    name: "ใบแจ้งความต้องการวัสดุ (Material Requirement)",
    abbr: "MRQ",
    prefix: "MRQ",
    purpose: "คำนวณวัสดุจาก BOM × จำนวนผลิต แล้วส่งจัดซื้อล่วงหน้าตาม Lead time",
    fields: [
      { key: "title", label: "รายการวัสดุ", type: "text", required: true },
      { key: "model", label: "สำหรับรุ่น", type: "model" },
      { key: "qty", label: "จำนวนที่ต้องการ", type: "number" },
      { key: "need", label: "ต้องการใช้วันที่", type: "date" },
      { key: "owner", label: "ผู้ขอ", type: "text" },
      { key: "date", label: "วันที่ออก", type: "date" },
    ],
    cols: ["model", "qty", "need", "owner"],
    statuses: [["ร่าง", "neutral"], ["ส่งจัดซื้อแล้ว", "info"], ["ของครบแล้ว", "good"], ["ล่าช้า", "critical"]],
    flow: ["ร่าง", "ส่งจัดซื้อแล้ว", "ของครบแล้ว"],
    closed: ["ของครบแล้ว"],
    samples: [
      { no: "MRQ-2026-001", status: "ส่งจัดซื้อแล้ว", title: "โซ่ลำเลียงอ้อย (Conveyor Chain)", model: "YT6500", qty: 3, need: "2026-10-05", owner: "ฝ่ายวางแผน", date: "2026-09-18" },
    ],
  },

  /* ---------------- Production ---------------- */
  dpr: {
    name: "รายงานการผลิตประจำวัน (Daily Report)",
    abbr: "DPR",
    prefix: "DPR",
    purpose: "ผลผลิตจริง กำลังคน และปัญหาของแต่ละไลน์ในแต่ละวัน — ข้อมูลตั้งต้นของทุกรายงาน",
    fields: [
      { key: "title", label: "งานที่ทำวันนี้", type: "text", required: true },
      { key: "line", label: "ไลน์ผลิต", type: "line" },
      { key: "date", label: "วันที่", type: "date" },
      { key: "output", label: "ผลผลิต (ชิ้นงาน/ขั้นตอนที่เสร็จ)", type: "number" },
      { key: "manpower", label: "กำลังคนที่มาทำงาน", type: "number" },
      { key: "owner", label: "หัวหน้ากะ", type: "text" },
      { key: "detail", label: "ปัญหา / หมายเหตุ", type: "textarea" },
    ],
    cols: ["line", "date", "output", "manpower"],
    statuses: [["ส่งแล้ว", "info"], ["รับทราบแล้ว", "good"]],
    flow: ["ส่งแล้ว", "รับทราบแล้ว"],
    closed: ["รับทราบแล้ว"],
    samples: [
      { no: "DPR-2026-001", status: "รับทราบแล้ว", title: "ประกอบโครงฐาน YT6500 เครื่องที่ 2", line: "ไลน์ประกอบ 1", date: "2026-09-23", output: 1, manpower: 11, owner: "หัวหน้าไลน์ประกอบ 1", detail: "รอโซ่ลำเลียง 2 ชม." },
    ],
  },
  mreq: {
    name: "ใบเบิกวัสดุ (Material Requisition)",
    abbr: "MR",
    prefix: "MR",
    purpose: "เบิกของจากคลังโดยอ้างอิงใบสั่งผลิต เพื่อให้ต้นทุนวัสดุลงถูกงาน",
    fields: [
      { key: "title", label: "รายการที่เบิก", type: "text", required: true },
      { key: "wo", label: "อ้างอิงใบสั่งผลิต", type: "text" },
      { key: "qty", label: "จำนวน", type: "number" },
      { key: "line", label: "ไลน์ที่เบิก", type: "line" },
      { key: "owner", label: "ผู้เบิก", type: "text" },
      { key: "date", label: "วันที่เบิก", type: "date" },
    ],
    cols: ["wo", "qty", "line", "date"],
    statuses: [["รออนุมัติ", "warning"], ["อนุมัติ", "info"], ["จ่ายของแล้ว", "good"], ["ปฏิเสธ", "critical"]],
    flow: ["รออนุมัติ", "อนุมัติ", "จ่ายของแล้ว"],
    closed: ["จ่ายของแล้ว", "ปฏิเสธ"],
    samples: [
      { no: "MR-2026-001", status: "รออนุมัติ", title: "ปลอกสายไฮดรอลิก 10 ชิ้น", wo: "WO-2026-0412", qty: 10, line: "ไลน์ประกอบ 1", owner: "ช่างประกอบ", date: "2026-09-23" },
    ],
  },
  saf: {
    name: "รายงานเหตุการณ์ความปลอดภัย / Near Miss",
    abbr: "SAF",
    prefix: "SAF",
    purpose: "รายงานเหตุเกือบเกิดอุบัติเหตุก่อนจะเกิดจริง พร้อมแนวทางแก้ไข",
    fields: [
      { key: "title", label: "เหตุการณ์", type: "text", required: true },
      { key: "line", label: "พื้นที่ / ไลน์", type: "line" },
      { key: "severity", label: "ระดับ", type: "select", options: ["เกือบเกิดเหตุ (Near Miss)", "บาดเจ็บเล็กน้อย", "บาดเจ็บหยุดงาน", "ทรัพย์สินเสียหาย"] },
      { key: "owner", label: "ผู้รายงาน", type: "text" },
      { key: "date", label: "วันที่เกิด", type: "date" },
      { key: "detail", label: "การแก้ไข / ป้องกัน", type: "textarea" },
    ],
    cols: ["line", "severity", "date"],
    statuses: [["เปิด", "warning"], ["กำลังแก้ไข", "info"], ["ปิดแล้ว", "good"]],
    flow: ["เปิด", "กำลังแก้ไข", "ปิดแล้ว"],
    closed: ["ปิดแล้ว"],
    samples: [],
  },

  /* ---------------- QC ---------------- */
  ncr: {
    name: "NCR — รายงานสิ่งที่ไม่เป็นไปตามข้อกำหนด",
    abbr: "NCR",
    prefix: "NCR",
    purpose: "บันทึกของเสีย/ข้อบกพร่องทุกครั้ง พร้อมการตัดสินใจว่าจะแก้ ใช้ คืน หรือทิ้ง",
    fields: [
      { key: "title", label: "ปัญหาที่พบ", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "found", label: "พบที่", type: "select", options: ["ตรวจรับวัตถุดิบ", "ระหว่างผลิต", "ตรวจก่อนส่งมอบ", "ลูกค้าแจ้ง"] },
      { key: "disposition", label: "การตัดสินใจ", type: "select", options: ["รอพิจารณา", "แก้ไข (Rework)", "ใช้ตามสภาพ", "คืนผู้ขาย", "ทิ้ง (Scrap)"] },
      { key: "wo", label: "อ้างอิงใบสั่งผลิต / PO", type: "text" },
      { key: "owner", label: "ผู้รับผิดชอบ", type: "text" },
      { key: "date", label: "วันที่พบ", type: "date" },
      { key: "detail", label: "สาเหตุ", type: "textarea" },
    ],
    cols: ["model", "found", "disposition", "date"],
    statuses: [["เปิด", "critical"], ["วิเคราะห์สาเหตุ", "warning"], ["กำลังแก้ไข", "info"], ["ปิดแล้ว", "good"]],
    flow: ["เปิด", "วิเคราะห์สาเหตุ", "กำลังแก้ไข", "ปิดแล้ว"],
    closed: ["ปิดแล้ว"],
    samples: [
      { no: "NCR-2026-001", status: "กำลังแก้ไข", title: "รอยเชื่อมโครงฐานไม่เต็มแนว", model: "YT6500", found: "ระหว่างผลิต", disposition: "แก้ไข (Rework)", wo: "WO-2026-0412", owner: "ไลน์เชื่อม", date: "2026-09-19", detail: "กระแสเชื่อมต่ำกว่ากำหนด" },
      { no: "NCR-2026-002", status: "เปิด", title: "เฟืองขับขนาดไม่ตรงแบบ", model: "YT7500", found: "ตรวจรับวัตถุดิบ", disposition: "คืนผู้ขาย", wo: "PO-2026-0318", owner: "QC", date: "2026-09-22", detail: "" },
    ],
  },
  capa: {
    name: "CAPA — การแก้ไขและป้องกัน",
    abbr: "CAPA",
    prefix: "CAPA",
    purpose: "แก้ที่ต้นเหตุไม่ให้ปัญหาเดิมเกิดซ้ำ และติดตามผลจนยืนยันว่าได้ผลจริง",
    fields: [
      { key: "title", label: "มาตรการ", type: "text", required: true },
      { key: "ref", label: "อ้างอิง NCR", type: "ref", refType: "ncr" },
      { key: "owner", label: "ผู้รับผิดชอบ", type: "text" },
      { key: "due", label: "กำหนดเสร็จ", type: "date" },
      { key: "detail", label: "ผลการติดตาม", type: "textarea" },
    ],
    cols: ["ref", "owner", "due"],
    statuses: [["เปิด", "warning"], ["กำลังดำเนินการ", "info"], ["ติดตามผล", "info"], ["ปิดแล้ว", "good"]],
    flow: ["เปิด", "กำลังดำเนินการ", "ติดตามผล", "ปิดแล้ว"],
    closed: ["ปิดแล้ว"],
    samples: [
      { no: "CAPA-2026-001", status: "กำลังดำเนินการ", title: "ตั้งค่ากระแสเชื่อมมาตรฐานและตรวจทุกต้นกะ", ref: "NCR-2026-001", owner: "หัวหน้าไลน์เชื่อม", due: "2026-10-03", detail: "" },
    ],
  },
  iqc: {
    name: "ตรวจรับวัตถุดิบ (Incoming Inspection)",
    abbr: "IQC",
    prefix: "IQC",
    purpose: "ตรวจของจากผู้ขายก่อนเข้าคลัง ของไม่ผ่านต้องไม่ถึงไลน์ผลิต",
    fields: [
      { key: "title", label: "รายการที่ตรวจ", type: "text", required: true },
      { key: "po", label: "อ้างอิง PO", type: "text" },
      { key: "supplier", label: "ผู้ขาย", type: "text" },
      { key: "qty", label: "จำนวนที่ตรวจ", type: "number" },
      { key: "owner", label: "ผู้ตรวจ", type: "text" },
      { key: "date", label: "วันที่ตรวจ", type: "date" },
    ],
    cols: ["po", "supplier", "qty", "date"],
    statuses: [["รอตรวจ", "warning"], ["ผ่าน", "good"], ["ผ่านแบบมีเงื่อนไข", "info"], ["ไม่ผ่าน", "critical"]],
    flow: ["รอตรวจ", "ผ่าน"],
    closed: ["ผ่าน", "ผ่านแบบมีเงื่อนไข", "ไม่ผ่าน"],
    samples: [
      { no: "IQC-2026-001", status: "ไม่ผ่าน", title: "ชุดเฟืองขับ (Drive Gear Set)", po: "PO-2026-0318", supplier: "ซัพพลายเออร์เฟือง", qty: 6, owner: "QC", date: "2026-09-22" },
    ],
  },
  fi: {
    name: "ตรวจสอบก่อนส่งมอบ (Final Inspection / PDI)",
    abbr: "FI",
    prefix: "FI",
    purpose: "ตรวจเครื่องทุกคันตาม Checklist ก่อนส่งให้ลูกค้า",
    fields: [
      { key: "title", label: "เลขเครื่อง (Serial)", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "wo", label: "อ้างอิงใบสั่งผลิต", type: "text" },
      { key: "owner", label: "ผู้ตรวจ", type: "text" },
      { key: "date", label: "วันที่ตรวจ", type: "date" },
      { key: "detail", label: "ข้อบกพร่องที่พบ", type: "textarea" },
    ],
    cols: ["model", "wo", "date"],
    statuses: [["รอตรวจ", "warning"], ["ผ่าน", "good"], ["ไม่ผ่าน-ส่งแก้ไข", "critical"]],
    flow: ["รอตรวจ", "ผ่าน"],
    closed: ["ผ่าน"],
    samples: [],
  },

  /* ---------------- Purchasing ---------------- */
  rfq: {
    name: "ขอราคาเปรียบเทียบ (RFQ)",
    abbr: "RFQ",
    prefix: "RFQ",
    purpose: "ขอราคาอย่างน้อย 3 ราย แล้วบันทึกเหตุผลที่เลือก ก่อนออก PO",
    fields: [
      { key: "title", label: "รายการที่ขอราคา", type: "text", required: true },
      { key: "pr", label: "อ้างอิง PR", type: "text" },
      { key: "suppliers", label: "ผู้ขายที่ขอราคา", type: "text" },
      { key: "selected", label: "ผู้ขายที่เลือก / เหตุผล", type: "text" },
      { key: "amount", label: "มูลค่า (บาท)", type: "number" },
      { key: "owner", label: "ผู้จัดซื้อ", type: "text" },
      { key: "date", label: "วันที่ขอราคา", type: "date" },
    ],
    cols: ["pr", "selected", "amount", "date"],
    statuses: [["ขอราคา", "info"], ["เปรียบเทียบ", "warning"], ["เลือกผู้ขายแล้ว", "good"], ["ยกเลิก", "critical"]],
    flow: ["ขอราคา", "เปรียบเทียบ", "เลือกผู้ขายแล้ว"],
    closed: ["เลือกผู้ขายแล้ว", "ยกเลิก"],
    samples: [
      { no: "RFQ-2026-001", status: "เปรียบเทียบ", title: "Servo Motor หุ่นยนต์เชื่อม", pr: "PR-2026-0144", suppliers: "3 ราย", selected: "", amount: 85000, owner: "ฝ่ายจัดซื้อ", date: "2026-09-16" },
    ],
  },
  sev: {
    name: "ประเมินผู้ขาย (Supplier Evaluation)",
    abbr: "SE",
    prefix: "SE",
    purpose: "ให้คะแนนคุณภาพ ส่งตรงเวลา และราคา เป็นรอบ เพื่อเลือกผู้ขายด้วยข้อมูล",
    fields: [
      { key: "title", label: "ชื่อผู้ขาย", type: "text", required: true },
      { key: "period", label: "รอบประเมิน", type: "text" },
      { key: "quality", label: "คุณภาพ (1–5)", type: "number" },
      { key: "delivery", label: "ส่งตรงเวลา (1–5)", type: "number" },
      { key: "price", label: "ราคา (1–5)", type: "number" },
      { key: "owner", label: "ผู้ประเมิน", type: "text" },
      { key: "date", label: "วันที่ประเมิน", type: "date" },
    ],
    cols: ["period", "quality", "delivery", "price"],
    statuses: [["ร่าง", "neutral"], ["ประเมินแล้ว", "good"]],
    flow: ["ร่าง", "ประเมินแล้ว"],
    closed: ["ประเมินแล้ว"],
    samples: [],
  },

  /* ---------------- Warehouse ---------------- */
  grn: {
    name: "ใบรับสินค้าเข้าคลัง (GRN)",
    abbr: "GRN",
    prefix: "GRN",
    purpose: "บันทึกของที่รับจริงเทียบกับ PO — รับเข้าคลังได้หลัง QC ตรวจผ่าน",
    fields: [
      { key: "title", label: "รายการที่รับ", type: "text", required: true },
      { key: "po", label: "อ้างอิง PO", type: "text" },
      { key: "supplier", label: "ผู้ขาย", type: "text" },
      { key: "qty", label: "จำนวนที่รับ", type: "number" },
      { key: "owner", label: "ผู้รับของ", type: "text" },
      { key: "date", label: "วันที่รับ", type: "date" },
    ],
    cols: ["po", "supplier", "qty", "date"],
    statuses: [["รอ QC ตรวจ", "warning"], ["รับเข้าคลังแล้ว", "good"], ["ส่งคืนผู้ขาย", "critical"]],
    flow: ["รอ QC ตรวจ", "รับเข้าคลังแล้ว"],
    closed: ["รับเข้าคลังแล้ว", "ส่งคืนผู้ขาย"],
    samples: [
      { no: "GRN-2026-001", status: "รอ QC ตรวจ", title: "ชุดเฟืองขับ (Drive Gear Set)", po: "PO-2026-0318", supplier: "ซัพพลายเออร์เฟือง", qty: 6, owner: "คลังสินค้า", date: "2026-09-22" },
    ],
  },
  stk: {
    name: "ตรวจนับสต็อก (Stock Count)",
    abbr: "STK",
    prefix: "STK",
    purpose: "นับของจริงเทียบยอดในระบบเป็นรอบ แล้วปรับยอดให้ตรง",
    fields: [
      { key: "title", label: "พื้นที่ / หมวดสินค้า", type: "text", required: true },
      { key: "items", label: "จำนวนรายการที่นับ", type: "number" },
      { key: "diff", label: "รายการที่ยอดไม่ตรง", type: "number" },
      { key: "owner", label: "ผู้นับ", type: "text" },
      { key: "date", label: "วันที่นับ", type: "date" },
    ],
    cols: ["items", "diff", "date"],
    statuses: [["วางแผน", "neutral"], ["กำลังนับ", "info"], ["ปรับยอดแล้ว", "good"]],
    flow: ["วางแผน", "กำลังนับ", "ปรับยอดแล้ว"],
    closed: ["ปรับยอดแล้ว"],
    samples: [],
  },

  /* ---------------- Maintenance ---------------- */
  mtr: {
    name: "ใบแจ้งซ่อม (Maintenance Request)",
    abbr: "MT",
    prefix: "MT",
    purpose: "ทุกคนแจ้งเครื่องเสียได้ทันที ฝ่ายซ่อมบำรุงเห็นคิวงานและติดตามจนซ่อมเสร็จ",
    fields: [
      { key: "title", label: "อาการ / ปัญหา", type: "text", required: true },
      { key: "machine", label: "เครื่องจักร", type: "text" },
      { key: "line", label: "ไลน์", type: "line" },
      { key: "priority", label: "ความเร่งด่วน", type: "select", options: ["ด่วนมาก (ไลน์หยุด)", "ด่วน", "ปกติ"] },
      { key: "owner", label: "ผู้แจ้ง", type: "text" },
      { key: "date", label: "วันที่แจ้ง", type: "date" },
    ],
    cols: ["machine", "line", "priority", "date"],
    statuses: [["แจ้งซ่อม", "warning"], ["กำลังซ่อม", "info"], ["รออะไหล่", "critical"], ["ซ่อมเสร็จ", "good"]],
    flow: ["แจ้งซ่อม", "กำลังซ่อม", "ซ่อมเสร็จ"],
    closed: ["ซ่อมเสร็จ"],
    samples: [
      { no: "MT-2026-001", status: "รออะไหล่", title: "หุ่นยนต์เชื่อมแกน 3 ไม่เคลื่อนที่", machine: "หุ่นยนต์เชื่อม #2", line: "ไลน์เชื่อม", priority: "ด่วน", owner: "ไลน์เชื่อม", date: "2026-09-15" },
    ],
  },
  pm: {
    name: "แผนบำรุงรักษาเชิงป้องกัน (PM)",
    abbr: "PM",
    prefix: "PM",
    purpose: "บำรุงรักษาตามรอบก่อนเครื่องเสีย ลดเวลาหยุดไลน์โดยไม่ได้วางแผน",
    fields: [
      { key: "title", label: "รายการ PM", type: "text", required: true },
      { key: "machine", label: "เครื่องจักร", type: "text" },
      { key: "freq", label: "รอบ", type: "select", options: ["รายสัปดาห์", "รายเดือน", "ราย 3 เดือน", "ราย 6 เดือน", "รายปี"] },
      { key: "due", label: "ครบกำหนด", type: "date" },
      { key: "owner", label: "ช่างผู้รับผิดชอบ", type: "text" },
    ],
    cols: ["machine", "freq", "due"],
    statuses: [["ตามแผน", "info"], ["เลยกำหนด", "critical"], ["ทำแล้ว", "good"]],
    flow: ["ตามแผน", "ทำแล้ว"],
    closed: ["ทำแล้ว"],
    samples: [
      { no: "PM-2026-001", status: "ตามแผน", title: "เปลี่ยนน้ำมันไฮดรอลิกเครื่องพับ", machine: "เครื่องพับเหล็ก CNC", freq: "ราย 6 เดือน", due: "2026-10-10", owner: "ฝ่ายซ่อมบำรุง" },
    ],
  },

  /* ---------------- Sales ---------------- */
  so: {
    name: "คำสั่งซื้อลูกค้า (Sales Order)",
    abbr: "SO",
    prefix: "SO",
    purpose: "ต้นทางของแผนผลิตทั้งหมด — ฝ่ายวางแผนใช้กำหนดล็อตและวันส่งมอบ",
    fields: [
      { key: "title", label: "ลูกค้า", type: "text", required: true },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "qty", label: "จำนวน (คัน)", type: "number" },
      { key: "due", label: "กำหนดส่งมอบ", type: "date" },
      { key: "owner", label: "พนักงานขาย", type: "text" },
      { key: "date", label: "วันที่รับคำสั่งซื้อ", type: "date" },
    ],
    cols: ["model", "qty", "due"],
    statuses: [["เสนอราคา", "neutral"], ["ยืนยันคำสั่งซื้อ", "info"], ["กำลังผลิต", "warning"], ["ส่งมอบแล้ว", "good"], ["ยกเลิก", "critical"]],
    flow: ["เสนอราคา", "ยืนยันคำสั่งซื้อ", "กำลังผลิต", "ส่งมอบแล้ว"],
    closed: ["ส่งมอบแล้ว", "ยกเลิก"],
    samples: [
      { no: "SO-2026-001", status: "กำลังผลิต", title: "บริษัท น้ำตาลพิษณุโลก จำกัด", model: "YT6500", qty: 3, due: "2026-11-15", owner: "ฝ่ายขาย", date: "2026-08-20" },
    ],
  },
  cc: {
    name: "ข้อร้องเรียนลูกค้า (Customer Complaint)",
    abbr: "CC",
    prefix: "CC",
    purpose: "รับเรื่องจากลูกค้า ส่งต่อ QC/วิศวกรรม และแจ้งผลกลับจนปิดเรื่อง",
    fields: [
      { key: "title", label: "เรื่องที่ร้องเรียน", type: "text", required: true },
      { key: "customer", label: "ลูกค้า", type: "text" },
      { key: "model", label: "รุ่นเครื่องจักร", type: "model" },
      { key: "owner", label: "ผู้รับเรื่อง", type: "text" },
      { key: "date", label: "วันที่รับเรื่อง", type: "date" },
      { key: "detail", label: "การแก้ไข / แจ้งผลลูกค้า", type: "textarea" },
    ],
    cols: ["customer", "model", "date"],
    statuses: [["รับเรื่อง", "warning"], ["กำลังแก้ไข", "info"], ["ปิดเรื่อง", "good"]],
    flow: ["รับเรื่อง", "กำลังแก้ไข", "ปิดเรื่อง"],
    closed: ["ปิดเรื่อง"],
    samples: [
      { no: "CC-2026-001", status: "ปิดเรื่อง", title: "ใบมีดสึกเร็วผิดปกติ", customer: "ลูกค้าไร่อ้อย จ.กำแพงเพชร", model: "YT6500", owner: "ฝ่ายขาย", date: "2026-08-28", detail: "ส่งต่อวิศวกรรม → ECR-2026-001" },
    ],
  },
};
